Merge origin/main into branch, resolve prudence.Rmd conflict
Co-authored-by: krlmlr <1741643+krlmlr@users.noreply.github.com>

diff --git a/.github/workflows/R-CMD-check.yaml b/.github/workflows/R-CMD-check.yaml
--- a/.github/workflows/R-CMD-check.yaml
+++ b/.github/workflows/R-CMD-check.yaml
@@ -10,6 +10,7 @@ on:
       - main
       - master
       - release
+      - next
       - cran-*
   pull_request:
     branches:
@@ -29,6 +30,14 @@ on:
         description: "Create a matrix of suggested dependencies"
         type: boolean
         default: false
+      run-rcc-full:
+        description: "Run rcc-full job"
+        type: boolean
+        default: false
+      run-rcc-suggests:
+        description: "Run rcc-suggests job"
+        type: boolean
+        default: false
   merge_group:
     types:
       - checks_requested
@@ -44,12 +53,19 @@ name: rcc
 jobs:
   rcc-smoke:
     runs-on: ubuntu-24.04
+
     outputs:
       sha: ${{ steps.commit.outputs.sha }}
       versions-matrix: ${{ steps.versions-matrix.outputs.matrix }}
       dep-suggests-matrix: ${{ steps.dep-suggests-matrix.outputs.matrix }}
 
     name: "Smoke test: stock R"
+
+    permissions:
+      contents: write
+      statuses: write
+      pull-requests: write
+      actions: write
 
     # Begin custom: services
     # End custom: services
@@ -60,17 +76,16 @@ jobs:
           ref: ${{ inputs.ref }}
 
       - name: Update status for rcc
+        if: github.actor != 'Copilot' && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
         # FIXME: Wrap into action
-        if: github.event_name == 'workflow_dispatch'
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
+          echo "Actor: ${{ github.actor }}"
+
           # Check status of this workflow
           state="pending"
           sha=${{ inputs.ref }}
-          if [ -z "${sha}" ]; then
-            sha=${{ github.head_ref }}
-          fi
           if [ -z "${sha}" ]; then
             sha=${{ github.sha }}
           fi
@@ -104,17 +119,18 @@ jobs:
         with:
           token: ${{ secrets.GITHUB_TOKEN }}
           cache-version: rcc-smoke-2
-          needs: check, website
+          needs: build, check, website
           # Beware of using dev pkgdown here, has brought in dev dependencies in the past
-          extra-packages: any::rcmdcheck r-lib/roxygen2 any::decor r-lib/styler r-lib/pkgdown deps::.
+          extra-packages: any::rcmdcheck r-lib/roxygen2 any::decor r-lib/pkgdown deps::.
 
+      - uses: ./.github/workflows/custom/after-install
+        if: hashFiles('.github/workflows/custom/after-install/action.yml') != ''
+
+      # Must come after the custom after-install workflow
       - name: Install package
         run: |
           _R_SHLIB_STRIP_=true R CMD INSTALL .
         shell: bash
-
-      - uses: ./.github/workflows/custom/after-install
-        if: hashFiles('.github/workflows/custom/after-install/action.yml') != ''
 
       - id: versions-matrix
         # Only run for pull requests if the base repo is different from the head repo, not for workflow_dispatch if not requested, always run for other events
@@ -126,11 +142,19 @@ jobs:
         if: github.event_name != 'workflow_dispatch' || inputs.dep-suggests-matrix
         uses: ./.github/workflows/dep-suggests-matrix
 
+      - id: repo-state
+        name: Determine repository state
+        uses: ./.github/workflows/repo-state
+
+      # Styling on foreign PRs works through the format-suggest workflow
+      - uses: ./.github/workflows/style
+        if: steps.repo-state.outputs.foreign != 'true' || steps.repo-state.outputs.is_pr != 'true'
+
+      # Snapshot tests can't work in a way similar to format-suggests
+      # because it requires running code which is a security risk on pull_request_target workflows
       - uses: ./.github/workflows/update-snapshots
         with:
           base: ${{ inputs.ref || github.head_ref }}
-
-      - uses: ./.github/workflows/style
 
       - uses: ./.github/workflows/roxygenize
 
@@ -159,14 +183,14 @@ jobs:
           echo -n "${{ steps.commit.outputs.sha }}" > rcc-smoke-sha.txt
         shell: bash
 
-      - uses: actions/upload-artifact@v4
+      - uses: actions/upload-artifact@v5
         with:
           name: rcc-smoke-sha
           path: rcc-smoke-sha.txt
 
       - name: Update status for rcc
         # FIXME: Wrap into action
-        if: always() && github.event_name == 'workflow_dispatch'
+        if: always() && (github.actor != 'Copilot') && (github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository)
         env:
           GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
         run: |
@@ -182,12 +206,42 @@ jobs:
             sha=${{ inputs.ref }}
           fi
           if [ -z "${sha}" ]; then
-            sha=${{ github.head_ref }}
-          fi
-          if [ -z "${sha}" ]; then
             sha=${{ github.sha }}
           fi
             sha=$(git rev-parse ${sha})
+
+          html_url=$(gh api \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            repos/${{ github.repository }}/actions/runs/${{ github.run_id }} | jq -r .html_url)
+
+          description="${{ github.workflow }} / ${{ github.job }}"
+
+          gh api \
+            --method POST \
+            -H "Accept: application/vnd.github+json" \
+            -H "X-GitHub-Api-Version: 2022-11-28" \
+            repos/${{ github.repository }}/statuses/${sha} \
+            -f "state=${state}" -f "target_url=${html_url}" -f "description=${description}" -f "context=rcc"
+        shell: bash
+
+      - name: Update status for rcc (Copilot)
+        # Update status directly when triggered by Copilot or bots, since they can't dispatch workflows
+        if: always() && (github.actor == 'Copilot')
+        env:
+          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
+        run: |
+          # Set status to success if job succeeded, failure otherwise
+          if [ "${{ job.status }}" == "success" ]; then
+            state="success"
+          else
+            state="failure"
+          fi
+          sha=${{ inputs.ref }}
+          if [ -z "${sha}" ]; then
+            sha=${{ github.sha }}
+          fi
+          sha=$(git rev-parse ${sha})
 
           html_url=$(gh api \
             -H "Accept: application/vnd.github+json" \
@@ -231,7 +285,7 @@ jobs:
 
     runs-on: ${{ matrix.os }}
 
-    if: ${{ needs.rcc-smoke.outputs.versions-matrix != '' }}
+    if: ${{ needs.rcc-smoke.outputs.versions-matrix != '' && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run-rcc-full)) }}
 
     name: 'rcc: ${{ matrix.os }} (${{ matrix.r }}) ${{ matrix.desc }}'
 
@@ -255,10 +309,22 @@ jobs:
           r-version: ${{ matrix.r }}
           cache-version: rcc-full-1
           token: ${{ secrets.GITHUB_TOKEN }}
-          needs: check
+          needs: build, check
 
       - uses: ./.github/workflows/custom/after-install
         if: hashFiles('.github/workflows/custom/after-install/action.yml') != ''
+
+      - name: Must allow NOTEs if packages are missing, even with _R_CHECK_FORCE_SUGGESTS_
+        run: |
+          if (Sys.getenv("RCMDCHECK_ERROR_ON") %in% c("", "note")) {
+            pkgs <- setdiff(desc::desc_get_deps()$package, "R")
+            installable <- vapply(pkgs, FUN.VALUE = logical(1), requireNamespace, quietly = TRUE)
+            if (any(!installable)) {
+              message("Missing packages: ", paste(pkgs[!installable], collapse = ", "))
+              cat('RCMDCHECK_ERROR_ON="warning"\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
+            }
+          }
+        shell: Rscript {0}
 
       - uses: ./.github/workflows/update-snapshots
         if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.full_name == github.repository
@@ -281,7 +347,7 @@ jobs:
 
     runs-on: ubuntu-22.04
 
-    if: ${{ needs.rcc-smoke.outputs.dep-suggests-matrix != '' }}
+    if: ${{ needs.rcc-smoke.outputs.dep-suggests-matrix != '' && (github.event_name == 'schedule' || (github.event_name == 'workflow_dispatch' && inputs.run-rcc-suggests)) }}
 
     name: Without ${{ matrix.package }}
 
@@ -301,7 +367,7 @@ jobs:
       - uses: ./.github/workflows/install
         with:
           cache-version: rcc-dev-${{ matrix.package }}-1
-          needs: check
+          needs: build, check
           extra-packages: "any::rcmdcheck any::remotes ."
           token: ${{ secrets.GITHUB_TOKEN }}
 
@@ -325,11 +391,6 @@ jobs:
 
       - uses: ./.github/workflows/custom/after-install
         if: hashFiles('.github/workflows/custom/after-install/action.yml') != ''
-
-      - name: Define _R_CHECK_FORCE_SUGGESTS_
-        run: |
-          cat('_R_CHECK_FORCE_SUGGESTS_=false\n', file = Sys.getenv("GITHUB_ENV"), append = TRUE)
-        shell: Rscript {0}
 
       - name: Must allow NOTEs, even with _R_CHECK_FORCE_SUGGESTS_
         run: |
